name: Feature Request
description: File a feature request
title: "[Feature Request]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        If this is about a specific bee, please report to the pack dev. We do not create bees, we just give tools to pack developers.
        If you do report a "feature", that is about a specific bee or set of bees, it will be instantly closed due to it most likely being
        an issue with the bees that pack developers added themselves and not our code.

  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when X happens.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Solution(s)
      description: A clear and concise description of what you want to happen.
      placeholder: When X happens Y should happen like this other thing when A happens.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Maybe X could also do Z when Y happens instead of X doing something when Y happens.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Mod Version
      description: What version of the mod are you on?
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: loader-version
    attributes:
      label: Mod Loader Version
      description: What version of the mod loader are you on?
      placeholder: 1.16.5 - 36.1.32
    validations:
      required: true

  #Add back when fabric version is here.
  #  - type: dropdown
  #    id: loader
  #    attributes:
  #      label: Mod Loader
  #      description: What mod loader are you using? (Not required as of right now)
  #      multiple: true
  #      options:
  #        - N/A
  #        - Forge
  #    validations:
  #      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: You may also give any additional information here.
    validations:
      required: false

  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Acknowledgement
      description: By submitting this issue, you agree that you read the terms at the top of the page.
      options:
        - label: I agree that I read the terms at the top of the page.
          required: true
