modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"
issueTrackerURL="https://github.com/Team-Resourceful/ResoucefulLibKt/issues/new/choose"

[[mods]]
    modId = "resourcefullibkt"
    version = "${version}"
    displayName = "Resourceful Lib Kotlin"
    authors = "ThatGravyBoat, Epic_Oreo"
    description = "Team Resourceful Library"

[[dependencies.resourcefullibkt]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.3.0-beta,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.resourcefullibkt]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.3,)"
    ordering = "NONE"
    side = "BOTH"
